apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yNTIuMTAuMjE6NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJEZXZPcHMxMjMhQCMiLCJhdXRoIjoiWVdSdGFXNDZSR1YyVDNCek1USXpJVUFqIn19fQ==
kind: Secret
metadata:
  name: nexus-creds
  namespace: default
type: kubernetes.io/dockerconfigjson
