apiVersion: v1
kind: Secret
metadata:
  name: nexus-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yNTIuMTAuMjE6NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJEZXZPcHMxMjMhQCMiLCJhdXRoIjoiWVdSdGFXNDZSR1YyVDNCek1USXpJVUFqIn19fQ==
