apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yNTIuMTAuMjE6NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ5b3VyX3Bhc3N3b3JkIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImF1dGgiOiJZV1J0YVc0NmVXOTFjbDl3WVhOemQyOXlaQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: nexus-creds
  namespace: default
type: kubernetes.io/dockerconfigjson
